CREATE SEQUENCE SEQ_ACIDENTES
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE TBL_ACIDENTES (
    ID INTEGER DEFAULT SEQ_ACIDENTES.NEXTVAL NOT NULL,
    LOCALIZACAO VARCHAR2(40) NOT NULL,
    GRAVIDADE VARCHAR2(20) NOT NULL,
    DATA_ACIDENTE DATE NOT NULL,
    HORARIO VARCHAR2(10) NOT NULL,
    DESCRICAO VARCHAR2(100) NOT NULL

);
